[package]
name = "profiles"
version = "0.6.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

profiles_integrity = { workspace = true }
hc_zome_profiles_coordinator = { git = "https://github.com/holochain-open-dev/profiles", rev = "b3f14fb9d7ceadf274dc4cb2d5971b88803f8af7" }