[package]
name = "craving"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "craving"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

craving_integrity = { workspace = true } 
