[package]
name = "profiles_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles_integrity"

[dependencies]
hc_zome_profiles_integrity = { git = "https://github.com/holochain-open-dev/profiles", rev = "570dbc9135242a419b47b316ae22825d5a2c2ef9" }
hdi = { workspace = true }

serde = { workspace = true }
