[package]
name = "cravings"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "cravings"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

cravings_integrity = { workspace = true }
